### ISSUE TITLE
Win 10 Medusa getting an error

### ISSUE THREAD

**Issue by MotleyC** [ratoaq2/knowit#21] opened 2019-06-19 00:56 UTC
2019-06-18 20:52:22 WARNING  SHOWQUEUE-REFRESH :: [74c3f12] An error occurred while parsing: \\Tower\Media\TV\90 Day Fiancé The Other Way\Season 01\90 Day Fiancé The Other Way - 1x04 - Big Expectations.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
{
    "info": {
        "duration": "0:43:09", 
        "muxing_app": "libebml v1.3.7 + libmatroska v1.5.0", 
        "date_utc": "2019-06-18 06:58:02", 
        "writing_app": "mkvmerge v34.0.0 ('Sight and Seen') 64-bit"
    }, 
    "video_tracks": [
        {
            "forced": false, 
            "display_height": 1080, 
            "language": "eng", 
            "default": true, 
            "aspect_ratio_type": 0, 
            "enabled": true, 
            "number": 1, 
            "crop": {}, 
            "height": 1080, 
            "width": 1920, 
            "codec_id": "V_MPEG4/ISO/AVC", 
            "stereo_mode": 0, 
            "lacing": false, 
            "type": 1, 
            "display_width": 1920, 
            "interlaced": false
        }
    ], 
    "tags": [
        {
            "simpletags": [
                {
                    "default": true, 
                    "name": "BPS", 
                    "language": "eng", 
                    "string": "95"
                }, 
                {
                    "default": true, 
                    "name": "DURATION", 
                    "language": "eng", 
                    "string": "00:43:08.017000000"
                }, 
                {
                    "default": true, 
                    "name": "NUMBER_OF_FRAMES", 
                    "language": "eng", 
                    "string": "765"
                }, 
                {
                    "default": true, 
                    "name": "NUMBER_OF_BYTES", 
                    "language": "eng", 
                    "string": "30918"
                }, 
                {
                    "default": true, 
                    "name": "_STATISTICS_WRITING_APP", 
                    "language": "eng", 
                    "string": "mkvmerge v34.0.0 ('Sight and Seen') 64-bit"
                }, 
                {
                    "default": true, 
                    "name": "_STATISTICS_WRITING_DATE_UTC", 
                    "language": "eng", 
                    "string": "2019-06-18 06:58:02"
                }, 
                {
                    "default": true, 
                    "name": "_STATISTICS_TAGS", 
                    "language": "eng", 
                    "string": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
                }
            ], 
            "targets": [
                {
                    "name": "TargetTypeValue", 
                    "level": 4, 
                    "data": 50, 
                    "position": 1633505376, 
                    "type": 1, 
                    "id": 26826, 
                    "size": 1
                }, 
                {
                    "name": "TagTrackUID", 
                    "level": 4, 
                    "data": 3042681426591102130, 
                    "position": 1633505380, 
                    "type": 1, 
                    "id": 25541, 
                    "size": 8
                }, 
                {
                    "name": "TargetType", 
                    "level": 4, 
                    "data": "MOVIE", 
                    "position": 1633505391, 
                    "type": 3, 
                    "id": 25546, 
                    "size": 5
                }
            ]
        }, 
        {
            "simpletags": [
                {
                    "default": true, 
                    "name": "BPS", 
                    "language": "eng", 
                    "string": "4917116"
                }, 
                {
                    "default": true, 
                    "name": "DURATION", 
                    "language": "eng", 
                    "string": "00:43:09.520000000"
                }, 
                {
                    "default": true, 
                    "name": "NUMBER_OF_FRAMES", 
                    "language": "eng", 
                    "string": "77608"
                }, 
                {
                    "default": true, 
                    "name": "NUMBER_OF_BYTES", 
                    "language": "eng", 
                    "string": "1591621540"
                }, 
                {
                    "default": true, 
                    "name": "_STATISTICS_WRITING_APP", 
                    "language": "eng", 
                    "string": "mkvmerge v34.0.0 ('Sight and Seen') 64-bit"
                }, 
                {
                    "default": true, 
                    "name": "_STATISTICS_WRITING_DATE_UTC", 
                    "language": "eng", 
                    "string": "2019-06-18 06:58:02"
                }, 
                {
                    "default": true, 
                    "name": "_STATISTICS_TAGS", 
                    "language": "eng", 
                    "string": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
                }
            ], 
            "targets": [
                {
                    "name": "TargetTypeValue", 
                    "level": 4, 
                    "data": 50, 
                    "position": 1633505754, 
                    "type": 1, 
                    "id": 26826, 
                    "size": 1
                }, 
                {
                    "name": "TagTrackUID", 
                    "level": 4, 
                    "data": 18181890257732997181, 
                    "position": 1633505758, 
                    "type": 1, 
                    "id": 25541, 
                    "size": 8
                }, 
                {
                    "name": "TargetType", 
                    "level": 4, 
                    "data": "MOVIE", 
                    "position": 1633505769, 
                    "type": 3, 
                    "id": 25546, 
                    "size": 5
                }
            ]
        }, 
        {
            "simpletags": [
                {
                    "default": true, 
                    "name": "BPS", 
                    "language": "eng", 
                    "string": "126767"
                }, 
                {
                    "default": true, 
                    "name": "DURATION", 
                    "language": "eng", 
                    "string": "00:43:09.632000000"
                }, 
                {
                    "default": true, 
                    "name": "NUMBER_OF_FRAMES", 
                    "language": "eng", 
                    "string": "60695"
                }, 
                {
                    "default": true, 
                    "name": "NUMBER_OF_BYTES", 
                    "language": "eng", 
                    "string": "41035003"
                }, 
                {
                    "default": true, 
                    "name": "_STATISTICS_WRITING_APP", 
                    "language": "eng", 
                    "string": "mkvmerge v34.0.0 ('Sight and Seen') 64-bit"
                }, 
                {
                    "default": true, 
                    "name": "_STATISTICS_WRITING_DATE_UTC", 
                    "language": "eng", 
                    "string": "2019-06-18 06:58:02"
                }, 
                {
                    "default": true, 
                    "name": "_STATISTICS_TAGS", 
                    "language": "eng", 
                    "string": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
                }
            ], 
            "targets": [
                {
                    "name": "TargetTypeValue", 
                    "level": 4, 
                    "data": 50, 
                    "position": 1633506144, 
                    "type": 1, 
                    "id": 26826, 
                    "size": 1
                }, 
                {
                    "name": "TagTrackUID", 
                    "level": 4, 
                    "data": 11286609223665873662, 
                    "position": 1633506148, 
                    "type": 1, 
                    "id": 25541, 
                    "size": 8
                }, 
                {
                    "name": "TargetType", 
                    "level": 4, 
                    "data": "MOVIE", 
                    "position": 1633506159, 
                    "type": 3, 
                    "id": 25546, 
                    "size": 5
                }
            ]
        }
    ], 
    "chapters": [], 
    "audio_tracks": [
        {
            "forced": false, 
            "language": "eng", 
            "default": true, 
            "output_sampling_frequency": 48000.0, 
            "enabled": true, 
            "number": 2, 
            "sampling_frequency": 24000.0, 
            "channels": 2, 
            "codec_id": "A_AAC", 
            "lacing": true, 
            "type": 2
        }
    ], 
    "recurse_seek_head": false, 
    "subtitle_tracks": [
        {
            "forced": false, 
            "language": "eng", 
            "default": false, 
            "enabled": true, 
            "number": 3, 
            "codec_id": "S_TEXT/UTF8", 
            "lacing": false, 
            "type": 17
        }
    ]
}
+-------------------------------------------------------+
Traceback (most recent call last):
  File "C:\Medusa\Medusa\ext\knowit\api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "C:\Medusa\Medusa\ext\knowit\providers\enzyme.py", line 135, in describe
    video_path=video_path, version=enzyme.__version__, data=json.dumps(data))
  File "C:\Medusa\Python\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Medusa\Python\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Medusa\Python\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Medusa\Python\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.timedelta(0, 2589, 632000) is not JSON serializable

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+

**Comment by FlyingPersian** [comment] 2019-06-24 19:24
Having the same issue on FreeNAS:

<details>
...
2019-06-24 19:29:43 WARNING  SHOWQUEUE-ADD :: [74c3f12] An error occurred while parsing: /media/shows/The OA/S01/The OA - S01E05 - Paradise.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                          4.0                          |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
{
    "info": {
        "duration": "1:00:17",
        "date_utc": "2016-12-19 07:19:29",
        "muxing_app": "libebml v1.3.4 + libmatroska v1.4.5",
        "writing_app": "mkvmerge v9.3.1 ('Mask Machine') 32bit"
    },
    "video_tracks": [
        {
            "type": 1,
            "number": 1,
            "language": "und",
            "enabled": true,
            "default": true,
            "forced": false,
            "lacing": false,
            "codec_id": "V_MPEG4/ISO/AVC",
            "width": 1280,
            "height": 720,
            "interlaced": false,
            "stereo_mode": 0,
            "crop": {},
            "display_width": 1280,
            "display_height": 720,
            "aspect_ratio_type": 0
        }
    ],
    "audio_tracks": [
        {
            "type": 2,
            "number": 2,
            "language": "und",
            "enabled": true,
            "default": true,
            "forced": false,
            "lacing": true,
            "codec_id": "A_AC3",
            "sampling_frequency": 48000.0,
            "channels": 6,
            "output_sampling_frequency": 48000.0
        }
    ],
    "subtitle_tracks": [],
    "chapters": [],
    "tags": [],
    "recurse_seek_head": false
}
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/usr/home/medusa/Medusa/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/usr/home/medusa/Medusa/ext/knowit/providers/enzyme.py", line 135, in describe
    video_path=video_path, version=enzyme.__version__, data=json.dumps(data))
  File "/usr/local/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'timedelta' is not JSON serializable

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2019-06-24 19:29:43 DEBUG    SHOWQUEUE-ADD :: [74c3f12] The OA: Setting the status from 'Wanted' to 'Downloaded' and quality 'N/A' to 'Unknown' based on file: /media/shows/The OA/S01/The OA - S01E05 - Paradise.mkv
...
</details>

**Comment by jjmulenex** [comment] 2019-11-22 16:09
same issue Ubumtu 18.04

**Comment by dirkr07** [comment] 2019-12-12 11:25
Same on Synology :)

**Comment by Sandermand** [comment] 2020-01-22 18:32
Same issue on Synology:

Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/SickBeard/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/volume1/@appstore/medusa/var/SickBeard/ext/knowit/providers/enzyme.py", line 135, in describe
    video_path=video_path, version=enzyme.__version__, data=json.dumps(data))
  File "/var/packages/python/target/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/var/packages/python/target/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/var/packages/python/target/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/var/packages/python/target/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.timedelta(0, 1430, 163000) is not JSON serializable

**Comment by brandnewant** [comment] 2020-03-08 12:31
Also getting this error on Synology

**Comment by cino** [comment] 2020-03-11 12:46
Also getting this message on Synology. 

Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/enzyme.py", line 131, in describe
    raise MalformedFileError
MalformedFileError

**Comment by akhlan** [comment] 2020-05-22 12:55
I have Python 3.5.6-8  on Synology but Medusa prefer use Python 2.7.14...

How force Medusa to use the last Python version ?
I have installed this package (https://github.com/SynoCommunity/spksrc/issues/3710#issuecomment-524808904) the last time but Synology use always the old Python

**Comment by ratoaq2** [comment] 2023-01-01 16:40
Fixed on master since #24 is a duplicate of this one

**Closed by ratoaq2** 2023-01-01 16:40 UTC
Labels: bug
